# Generated by Django 5.0.4 on 2024-04-05 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nombre_joueur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resultat_team_dom', models.IntegerField(default=0)),
                ('resultat_team_ext', models.IntegerField(default=0)),
                ('team_dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_domicile', to='matchs.team')),
                ('team_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_exterieur', to='matchs.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('matchs_tournament', models.ManyToManyField(to='matchs.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='idTournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchs.tournament'),
        ),
    ]
