# Generated by Django 4.2.11 on 2024-04-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='nombre_joueur',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='matchs_tournament',
        ),
        migrations.AlterField(
            model_name='match',
            name='idTournament',
            field=models.ForeignKey(blank=None, default=None, on_delete=django.db.models.deletion.CASCADE, to='matchs.tournament'),
        ),
    ]
